#!/bin/sh
npm run build
mkdir /tmp/web-components-chat
cp -R public/* /tmp/web-components-chat
git checkout gh-pages
rm  README.md rollup.config.js package.json package-lock.json
rm -Rf ./scripts
rm -Rf ./src
rm -Rf ./public
cp -R /tmp/web-components-chat/* ./
git add .
git commit -m "Publishing docs for $(git log -1 --pretty=%B)"
git push origin gh-pages
git checkout master
